# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  push:
    branches:
     - '**'
    tags-ignore:
     - v*

name: Validate

jobs:
  check:
  lints-spec:
    name: Lint Support Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check RPM spec files Compliance
        run: echo "TODO: #1"
  lints-others:
    name: Lint Support Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Check EditorConfig Compliance
        uses: editorconfig-checker/action-editorconfig-checker@v1

  lints:
    name: Lint RPM Spec files & Support Files
    runs-on: ubuntu-latest
    needs: [lints-spec, lints-others]
    steps:
     - run: echo "All lints successful"
